name: loading_modal_button
description: Buttons that show a loading modal when pressed. And after finish loading, you can execute a function.
version: 1.1.5
homepage: https://github.com/sukekyo000/loading_modal_button

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: